#pragma once
#include <d3d9.h>

#define g_Direct3D ((LPDIRECT3D9)0x00B33A94)

int __stdcall CDirect3D_Create();
LPDIRECT3DDEVICE9 __stdcall CDirect3D_GetDevice();
void __stdcall CDirect3D_DrawText(int32 x, int32 y, int32 colorRGB, const char* lpChText);
void __stdcall CDirect3D_DrawTextCustom(int32 x, int32 y, int32 colorRGB, const char* lpChText, UINT format, int maxWidth);






enum D3D9DeviceFunctions {
    F_QueryInterface = 0,
    F_AddRef = 1,
    F_Release = 2,
    F_TestCooperativeLevel = 3,
    F_GetAvailableTextureMem = 4,
    F_EvictManagedResources = 5,
    F_GetDirect3D = 6,
    F_GetDeviceCaps = 7,
    F_GetDisplayMode = 8,
    F_GetCreationParameters = 9,
    F_SetCursorProperties = 10,
    F_SetCursorPosition = 11,
    F_ShowCursor = 12,
    F_CreateAdditionalSwapChain = 13,
    F_GetSwapChain = 14,
    F_GetNumberOfSwapChains = 15,
    F_Reset = 16,
    F_Present = 17,
    F_GetBackBuffer = 18,
    F_GetRasterStatus = 19,
    F_SetDialogBoxMode = 20,
    F_SetGammaRamp = 21,
    F_GetGammaRamp = 22,
    F_CreateTexture = 23,
    F_CreateVolumeTexture = 24,
    F_CreateCubeTexture = 25,
    F_CreateVertexBuffer = 26,
    F_CreateIndexBuffer = 27,
    F_CreateRenderTarget = 28,
    F_CreateDepthStencilSurface = 29,
    F_UpdateSurface = 30,
    F_UpdateTexture = 31,
    F_GetRenderTargetData = 32,
    F_GetFrontBufferData = 33,
    F_StretchRect = 34,
    F_ColorFill = 35,
    F_CreateOffscreenPlainSurface = 36,
    F_SetRenderTarget = 37,
    F_GetRenderTarget = 38,
    F_SetDepthStencilSurface = 39,
    F_GetDepthStencilSurface = 40,
    F_BeginScene = 41,
    F_EndScene = 42,
    F_Clear = 43,
    F_SetTransform = 44,
    F_GetTransform = 45,
    F_MultiplyTransform = 46,
    F_SetViewport = 47,
    F_GetViewport = 48,
    F_SetMaterial = 49,
    F_GetMaterial = 50,
    F_SetLight = 51,
    F_GetLight = 52,
    F_LightEnable = 53,
    F_GetLightEnable = 54,
    F_SetClipPlane = 55,
    F_GetClipPlane = 56,
    F_SetRenderState = 57,
    F_GetRenderState = 58,
    F_CreateStateBlock = 59,
    F_BeginStateBlock = 60,
    F_EndStateBlock = 61,
    F_SetClipStatus = 62,
    F_GetClipStatus = 63,
    F_GetTexture = 64,
    F_SetTexture = 65,
    F_GetTextureStageState = 66,
    F_SetTextureStageState = 67,
    F_GetSamplerState = 68,
    F_SetSamplerState = 69,
    F_ValidateDevice = 70,
    F_SetPaletteEntries = 71,
    F_GetPaletteEntries = 72,
    F_SetCurrentTexturePalette = 73,
    F_GetCurrentTexturePalette = 74,
    F_SetScissorRect = 75,
    F_GetScissorRect = 76,
    F_SetSoftwareVertexProcessing = 77,
    F_GetSoftwareVertexProcessing = 78,
    F_SetNPatchMode = 79,
    F_GetNPatchMode = 80,
    F_DrawPrimitive = 81,
    F_DrawIndexedPrimitive = 82,
    F_DrawPrimitiveUP = 83,
    F_DrawIndexedPrimitiveUP = 84,
    F_ProcessVertices = 85,
    F_CreateVertexDeclaration = 86,
    F_SetVertexDeclaration = 87,
    F_GetVertexDeclaration = 88,
    F_SetFVF = 89,
    F_GetFVF = 90,
    F_CreateVertexShader = 91,
    F_SetVertexShader = 92,
    F_GetVertexShader = 93,
    F_SetVertexShaderConstantF = 94,
    F_GetVertexShaderConstantF = 95,
    F_SetVertexShaderConstantI = 96,
    F_GetVertexShaderConstantI = 97,
    F_SetVertexShaderConstantB = 98,
    F_GetVertexShaderConstantB = 99,
    F_SetStreamSource = 100,
    F_GetStreamSource = 101,
    F_SetStreamSourceFreq = 102,
    F_GetStreamSourceFreq = 103,
    F_SetIndices = 104,
    F_GetIndices = 105,
    F_CreatePixelShader = 106,
    F_SetPixelShader = 107,
    F_GetPixelShader = 108,
    F_SetPixelShaderConstantF = 109,
    F_GetPixelShaderConstantF = 110,
    F_SetPixelShaderConstantI = 111,
    F_GetPixelShaderConstantI = 112,
    F_SetPixelShaderConstantB = 113,
    F_GetPixelShaderConstantB = 114,
    F_DrawRectPatch = 115,
    F_DrawTriPatch = 116,
    F_DeletePatch = 117,
    F_CreateQuery = 118,
    D3D9_DEVICE_FUNCTION_COUNT
};

void D3DHook_Init();